# Generated by Django 4.2.1 on 2023-05-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0004_rename_phone_employees_phone_emp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='phone_emp',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='employees',
            name='address',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
